### ISSUE TITLE
Add Rate-halving implementation separately

### ISSUE THREAD

**Issue by Viyom** [Avinash369/Rate-Halving-in-ns-3#1]
You have added the whole ns- 3 code along with Rate-halving implementation in a single commit.
It is difficult to find the changes in that. Please split "Added Rate Halving Implementation File" commit into two commits: 1) Add Initial code  2) Add Rate Halving Implementation

**Comment by Avinash369** [comment]
Sir,
I have changed the commits. Sorry for being late.
