### ISSUE TITLE
Fork latest ns-3 dev and add your commits on top of it

### ISSUE THREAD

**Issue by ShikhaBakshi** [Avinash369/Rate-Halving-in-ns-3#2]
ns-3 requires the complete commit history to merge any feature in the mainline. Also if you have not forked the main repo of ns-3,  you won't be able to create a merge request.

**Comment by Avinash369** [comment]
I have forked and cloned the repo of ns-3 from gitlab. Should I push the rate halving codes now or after the final evaluation?

**Comment by mohittahiliani** [comment]
After the final evaluation.
